#05_0006_BUSCADOR_Verificar_funcionalidad_textbox_buscador
#05_0007_BUSCADOR_Verificar_desplazamiento_letras_teclado_buscador
#05_0008_BUSCADOR_Verificar_funcionalidad_espacio_teclado_buscador
#05_0009_BUSCADOR_Verificar_funcionalidad_Borrar_Todo_Teclado_buscador
#05_0010_BUSCADOR_Verificar_funcionalidad_borrar_Teclado_buscador